### ISSUE TITLE
MDS API "Get URL for DOI" fails once the DOI is registered

### ISSUE THREAD

**Issue by MattBlissett** [datacite/poodle#10] opened 2018-08-07 15:43 UTC
Newly-created DOIs seem to return 404 when requesting their URL; at least for a while.

Steps to reproduce:

1. Register metadata:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd" xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <identifier identifierType="DOI">10.15468/gbif.1533655352</identifier>
    <creators>
        <creator>
            <creatorName>Matt</creatorName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="orcid.org">0000-0003-0623-6682</nameIdentifier>
        </creator>
    </creators>
    <titles>
        <title xml:lang="eng">reserve test</title>
    </titles>
    <publisher>GBIF</publisher>
    <publicationYear>2018</publicationYear>
    <resourceType resourceTypeGeneral="Dataset"/>
</resource>
```

```
curl -X POST -H "Content-Type:application/xml;charset=UTF-8" -i --user ****:**** -d @metadata.xml https://mds.test.datacite.org/metadata
```

Returns `201 Created` as expected.

2. Request the URL for the DOI (check #7 is now fixed):

```
curl -i --user **** https://mds.test.datacite.org/doi/10.15468/gbif.1533655352
```

`204 No Content`, excellent.

3. Create/register DOI:

```
curl -X PUT -H "Content-Type:text/plain;charset=UTF-8" -i --user **** -d "doi=10.15468/gbif.1533655352"$'\n'"url=http://example.org/" https://mds.test.datacite.org/doi/10.15468/gbif.1533655352
```

`201 Created` as expected, and it now shows as "Findable" in Fabrica.

4. Repeat step 2, request the URl for the DOI:

```
curl -i --user **** https://mds.test.datacite.org/doi/10.15468/gbif.1533655352
```

Returns `404 Not Found`, I expected `200` and `http://example.org/`.

With live DOIs, a recent one that was returning 404 about 5 minutes ago is now returning 200. Is there a predictable delay? On the test system, a DOI from almost an hour ago still returns 404 (`curl ... https://mds.test.datacite.org/doi/10.15469/gbif.3128360660081335`)

**Comment by richardhallett** [comment] 2018-08-28 08:07
I believe this is actually related to #12 which was caused by the wrong handle server responding with the URL update information for the test system.

In addition there is a slight delay potentially with updating URL's this is as expected as we want do background queueing of requests to ensure updates can be scaled across our services. Normally this should be within minutes however if you are requesting immediately after there is a potential you will not get the update back immediately.

I hope that answers your questions above and explains the 404, closing issue for now.

**Closed by richardhallett** 2018-08-28 08:07 UTC
Labels: bug, ready
